# Generated by Django 4.2.3 on 2023-12-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="btc_address",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="eth_address",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="usdt_address",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
