# Generated by Django 4.2.3 on 2023-12-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="plan_interval_processed",
            field=models.BooleanField(default=False),
        ),
    ]
