# Generated by Django 4.2.3 on 2024-01-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0003_alter_deposit_options_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="plan_interval_processed",
        ),
        migrations.AddField(
            model_name="transaction",
            name="interval_count",
            field=models.IntegerField(default=0),
        ),
    ]
