# Generated by Django 4.2.3 on 2024-01-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0004_remove_transaction_plan_interval_processed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="plan_interval_processed",
            field=models.BooleanField(default=False),
        ),
    ]
