# Generated by Django 4.2.3 on 2024-01-05 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0005_transaction_plan_interval_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 12, 14, 18, 12, 107701, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
