# Generated by Django 4.2.3 on 2024-01-06 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0008_alter_transaction_expiry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 13, 19, 20, 28, 474063, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
