# Generated by Django 4.2.3 on 2024-01-06 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0009_alter_transaction_expiry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="days_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 13, 19, 40, 0, 419257, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
