# Generated by Django 4.2.3 on 2024-01-18 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0010_transaction_days_count_alter_transaction_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="total_balance",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 25, 6, 39, 16, 815773, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
