# Generated by Django 4.2.3 on 2024-01-18 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0011_remove_user_total_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 25, 8, 21, 17, 673858, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
