# Generated by Django 4.2.3 on 2023-12-17 16:28

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserComplaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("question", models.CharField(max_length=50)),
                ("question_details", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "User Complaints",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="plan",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="Plan", max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("initial", models.CharField(default="BTC", max_length=7)),
                (
                    "image",
                    models.ImageField(
                        default="product.jpg", upload_to=core.models.user_directory_path
                    ),
                ),
                ("least_amount", models.IntegerField(default="100")),
                ("max_amount", models.IntegerField(default="100")),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                            ("hourly", "hourly"),
                        ],
                        default="daily",
                        max_length=16,
                    ),
                ),
                (
                    "invested_amount",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=1000
                    ),
                ),
                (
                    "percentage_return",
                    models.DecimalField(
                        decimal_places=2, default="1.99", max_digits=1000
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not processed", "Not Processed"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                        ],
                        default="in_review",
                        max_length=16,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Plans",
            },
        ),
    ]
