# Generated by Django 4.2.3 on 2023-12-19 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_btcaddress_ethaddress_otheraddress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otheraddress",
            options={"verbose_name_plural": "Other Address"},
        ),
        migrations.AlterModelOptions(
            name="usercomplaints",
            options={"verbose_name_plural": "Users Complaints"},
        ),
    ]
